### ISSUE TITLE
Can't filter out the old Genesis core

### ISSUE THREAD

**Issue by ghost** [theypsilon/Update_All_MiSTer#108]
Hi.
Any idea how to get rid of the deprecated genesis core?
If i filter it out in downloader.ini with !genesis it also removes the new Mega Drive core.

regards

**Comment by theypsilon** [comment]
There is no way right now, I was thinking of adding an additional filter, but after talking to Sorgelig I don't think is worth expending time on that. Genesis core will be removed "soon" according to him

**Comment by Yamato-san** [comment]
Hi,
sorry, to reply to such an old "closed" topic. But as 6 months have passed by now I would kindly like to ask if there is a new solution now which I am not aware of? I still delete the old core by hand after each update all process. I guess many do so. I feel like this issue is not really completed.
Thank you!

**Comment by theypsilon** [comment]
You are right, I'll try to address it soon.

**Comment by theypsilon** [comment]
That's done now, add `!genesis-core` to your filter to remove the old genesis core

**Comment by Yamato-san** [comment]
Thank you so much!
