### ISSUE TITLE
Fresh install put in /media/fat MiSTer_example.ini instead of MiSTer_example.ini, caused HDMI to not display on large screen

### ISSUE THREAD

**Issue by drag0nneus** [theypsilon/Update_All_MiSTer#114]
For some reason when I had upgraded Mister using the update_all script, I couldnt get HDMI out to work on a screen larger than 20"
I ran a fresh install on a new SD card and noticed that the MiSTer.ini file was missing and in its place again was MiSTer_example.ini

Downloaded this MiSTer.ini  from here now screen is fine

**Comment by theypsilon** [comment]
Hey, thanks for opening an issue. If there is no MiSTer.ini, the default values are used, so MiSTer.ini is not required for proper operation. If the default values are not working for your screen and you don't have any special setup, please report it here, because it should be fixed in the firmware side: https://github.com/MiSTer-devel/Main_MiSTer
