### ISSUE TITLE
/media/fat/Scripts/update_all.sh: line 103: ho: command not found

### ISSUE THREAD

**Issue by sofakng** [theypsilon/Update_All_MiSTer#25]
I've just run the update_all.sh script (v1.3) and when it finished it displayed the following error:

`/media/fat/Scripts/update_all.sh: line 103: ho: command not found
`

I've tried to upload the log to pastebin but it's too large (527 KB).  However, the error doesn't appear in the log so I think it's something trying to run at the very end of the updater?

**Comment by theypsilon** [comment]
This is gonna be a wild guess. Did you copy the update_all.sh file to your SD card via FTP?

The error shows that the script run well, but the update_all.sh file is corrupted in some way. The good news is that in following runs of update_all.sh , that error shouldn't happen anymore, because I'm updating the script if it does't seem to be right (please check that if you have the time). The bad news, is that I don't know why people (actually I only recall 3 cases) are having corrupted update_all.sh files in their MiSTer in the first place, and I haven't been able to replicate that error ever myself.

But, I recall that in one of the cases, the user copied update_all.sh to the SD via FTP. That's why I asked you that. In any case, how did you copy the file to your SD?

Thanks for contributing by opening this issue.

**Comment by theypsilon** [comment]
No context so far. Will reopen if more information comes.
