### ISSUE TITLE
Just static after update_all ran today

### ISSUE THREAD

**Issue by birdybro** [theypsilon/Update_All_MiSTer#28]
I ran the update_all and upon reboot it was just static. appeared as though the MiSTer main framework, or menu core, or something on the linux side must have been messed up. I got another SD card, ran the newest release of the sd card installer from sorg, and overwrote all the files on the one that wasn't working from the new ones. It then booted. Not sure what happened, but could it be that the linux files extracting to do their update screwed something up?

**Comment by theypsilon** [comment]
Yeah, it looks like one of these 3 components was wrongly downloaded for you. Or maybe, your SD card got corrupted. If that was the case, you could confirm it by trying to access it in your PC.

Coming back to these 3 components, as you might know, the main framework, the menu core, and Linux are actually downloaded by the official https://github.com/MiSTer-devel/Updater_script_MiSTer script, and "Update All" is just downloading that script and executing it. Then, it sounds like the problem is not specific to "Update All"

Probably it was just a fluke in the internet connection between your device and GitHub that affected your downloading. If that is the case, you might want to check your wifi dongle, in case you use one, because it might be erratic. And if was just only a very remote fluke, you shouldn't experience the same problem anymore.

**Comment by birdybro** [comment]
Yeah I'm chalking it up to a fluke. I actually had to stop using a wifi dongle, was really inconsistent for me despite using the approved dongle (3 different ones, i happened to have all of them coincidentally). I switched over to a wifi-to-ethernet bridge on my rpi4 which has been far superior. Since rewriting over it with the files from the sd card installer from sorg, then I think your assessment is correct.
