### ISSUE TITLE
Wallpapers

### ISSUE THREAD

**Issue by stefanerwinmayer** [theypsilon/Update_All_MiSTer#36]
Are you interested in adding a script that downloads wallpapers?

This one is an example:
https://github.com/RetroDriven/MiSTerWallpapers

Mind RetroDriven has stated he will discontinue his scripts as of now.

**Comment by theypsilon** [comment]
Hey, thanks for asking.

I'm not planning on adding a wallpapers script to Update All. The reason is that I think is more helpful if I keep the scope on updating cores, and making them operational from the get-go.

If I'd open the scope to cover literally everything that could be updated in the MiSTer ecosystem, I'm afraid Update All could become too big, too hard to maintain and probably also much more confusing to use for the average user.

**Comment by stefanerwinmayer** [comment]
Sensible. Thank you for your consideration.
