### ISSUE TITLE
corrupted rbf not replaced

### ISSUE THREAD

**Issue by juri74** [theypsilon/Update_All_MiSTer#42]
if during update something goes wrong and a rbf is not downloaded fully, it remain truncated on sd and a new run of the script do not fix the situation. i have to manually remove the partial downloaded file

**Comment by theypsilon** [comment]
Hey. This issue is inherited from the regular updater, which is used by this script, and would need a major refactor there in order to fix it. You may send a PR there if you want to tackle that: https://github.com/MiSTer-devel/Updater_script_MiSTer

For now, your only solution is deleting the file, and forcing a full resync. If you don't want to manually delete the files, you could clear all cores instead. Go to the Misc menu in the Settings Screen and select that option there, it should be safe if you don't have any custom/old folder structure in your SD.

**Comment by juri74** [comment]
thank you, didn't know about that. thank you again
