### ISSUE TITLE
Choosing which arcade games to keep updated

### ISSUE THREAD

**Issue by manast** [theypsilon/Update_All_MiSTer#61]
I wonder if it is possible to just keep updated a selection of Arcade roms? 

Often you only want to keep a smaller subset of all the games, a reason could be that you are using mister in a arcade cabinet and you do not want to download/update all vertical games, or it could be that you do not have more than 32Mb ram and you want to skip all games that require more memory than that. It could also just be that you are only interested in a few games that you like and not the rest...

**Comment by theypsilon** [comment]
There is a way of filtering, through tuning the update.ini with the REPOSITORIES_FILTER parameter like this:

![image](https://user-images.githubusercontent.com/852246/128631147-b05c2601-d32e-4667-82f4-33f1e57de6fc.png)

Definitely not the friendlies option, but possible. There is also the possibility of filtering them out with the Arcade Organizer. The 2.0 version of the AO is in Beta, and you can activate it like this: https://twitter.com/josembarroso/status/1421502906335997957

If you would like to still deactivate the arcades from being updated, I would like to understand something. Would you like to stop updating them just because of the lack of space on your SD card, or because the updater script takes too long to go through all the arcades?

**Comment by manast** [comment]
> If you would like to still deactivate the arcades from being updated, I would like to understand something. Would you like to stop updating them just because of the lack of space on your SD card, or because the updater script takes too long to go through all the arcades?

For both reasons, it takes a lot of space and it takes much longer to update. 

How would you use the filter option for arcade roms?

**Comment by theypsilon** [comment]
I think it would have to be `REPOSITORIES_FILTER="Arcade-Galaxian Arcade-IronHorse"` for example, if you only want to update these two cores.

You may also use the `REPOSITORIES_NEGATIVE_FILTER`, which does the opposite thing. It's all documented in the official updater:

![image](https://user-images.githubusercontent.com/852246/128640198-201c1e3a-aa8b-4ca8-aa25-1a6536219e90.png)

If your concern is specially the speed, things will get much quicker in the future, but you would have to be patient for the time being.

**Comment by matijaerceg** [comment]
Is update_all.sh supposed to respect the REPOSITORIES_NEGATIVE_FILTER from update.ini?

I have the following code in update.ini, but update_all still downloaded all available cores:
`REPOSITORIES_NEGATIVE_FILTER="Arcadia Astrocade AY-3-8500 ChannelIF Odyssey2 VC4000 Vectrex WonderSwan AcornAtom AcornElectron AliceMC10 Altair8800 Amstrad-PCW Amstrad Apogee Apple-I Apple-II Aquarius Archie BBCMicro BK0011M CoCo2 CoCo3 EDSAC Galaksija Interact Jupiter Laser310 MacPlus MultiComp Ondra ORAO Oric PC88 PDP1 PET2001 PMD85 QL RX78 SAMCoupe SharpMZ SordM5 Specialist Svi328 TatungEinstein Ti994a TRS-80 TSConf UK101 Vector-06C zx48 ZK81 ZXNext"`

**Comment by theypsilon** [comment]
Hi @matijaerceg , update.ini is no longer used. Now this has to be adapted to the new filter systems in downloader.ini
Here is the documentation: https://github.com/MiSTer-devel/Downloader_MiSTer/blob/main/docs/download-filters.md
You can basically copy paste all the terms to the new `filters =` field prepending a exclamation mark to each one of them (!), and it should work.
Here is a video of that process: https://www.youtube.com/watch?v=0gdr5Vv3obc

**Comment by matijaerceg** [comment]
@theypsilon thank you so much for your guidance. Just to confirm, does update_all respect these downloader.ini settings?

**Comment by theypsilon** [comment]
Yea
