### ISSUE TITLE
Request to add tty2oled to update_all

### ISSUE THREAD

**Issue by ojaksch** [theypsilon/Update_All_MiSTer#65]
I'm a co-maintainer of tty2oled and want to ask to add our updater script to your update_all .
Script is simply called by invoking _/media/fat/Scripts/update_tty2oled.sh_ - and that's all.

https://misterfpga.org/viewtopic.php?f=9&t=1887
https://github.com/venice1200/MiSTer_tty2oled/

**Comment by theypsilon** [comment]
Hi, there is a way to integrate additional scripts and files with the Downloader 1.2 release.

It's with the custom database feature: https://github.com/MiSTer-devel/Downloader_MiSTer/blob/main/docs/custom-databases.md

With it, people will be able to get your updater and/or your pictures for the screen.

Here I made a database that would get your updater file and place it in the Scripts folder.

```json
{
    "base_files_url": "",
    "db_files": [],
    "db_id": "tty2oled_files",
    "db_url": "https://raw.githubusercontent.com/venice1200/MiSTer_tty2oled/main/tty2oleddb.json",
    "default_options": {},
    "files": {
        "Scripts/update_tty2oled.sh": {
            "hash": "9962716a2d380541ed867a11c031affc",
            "size": 4942,
            "url": "https://raw.githubusercontent.com/venice1200/MiSTer_tty2oled/9687e7b044e0f927db8dedbf9a23393e8e74a31a/update_tty2oled.sh"
        }
    },
    "folders": {
        "Scripts": {}
    },
    "timestamp": 1636227177,
    "zips": {}
}
```

Just host this file, and then people will be able to integrate it by just adding a couple of lines to their `downloader.ini` file

```ini
[tty2oled_files]
db_url = https://raw.githubusercontent.com/venice1200/MiSTer_tty2oled/main/tty2oleddb.json
```

If you give support to this, I will add the `downloader.ini` setup as a option in the Settings Screen from update_all.

**Comment by ojaksch** [comment]
Great to hear, many thanks!
tty2oleddb.json is setup, online and accessable. Only change I suggest is to change uri to

> "url": "https://raw.githubusercontent.com/venice1200/MiSTer_tty2oled/main/update_tty2oled.sh"

We would be glad to see this added to update_all. Let's see how this works then.

**Comment by theypsilon** [comment]
That's also good, the only thing you need to care is to update the hash and size fields if you change the file.

Also, ideally you should keep the same db_id and same database url for `tty2oleddb.json` that you have now.

When you maintain your project in the future, consider using this database for also downloading the pictures. That way, users will only need to run one single script to be up-to-date.

I've integrated this option in Update All, under the Misc menu.

![image](https://user-images.githubusercontent.com/852246/140651974-02f15b23-a92d-49fb-868f-4aee6ed58595.png)

Let me know if you need any help with this in the future. And congrats for the awesome project you guys are pulling off.

**Comment by venice1200** [comment]
Many Thanks for your support!
Aloha to Berlin

**Comment by ojaksch** [comment]
> Let me know if you need any help with this in the future. And congrats for the awesome project you guys are pulling off.

Thanks for implementing! Script is working and downloading (but not executing) our update_tty2oled.sh
We're considering in bringing all pictures/URLs to a json db, but we had poor experiences by downloading so much pictures from github (>500 pictures and still growing). github is missing timestamps, offers relatively slow responsiness and more, so we changed our updater to use rsync, which is downloading/syncing hundreds of files in just a few secs from a dedicated domain (synced git repo).

I've played a little bit with update_all.sh this morning, looking for a satisfying solution how to get update_tty2oled.sh executed after running update_all.sh and ended up choosing this oneliner at the end of the update_all.sh script, just before exiting.
Would be great if you would add this oneliner!

```[ ${TTY2OLED_FILES_DOWNLOADER} = "true" ] && [ -e /media/fat/Scripts/update_tty2oled.sh ] && update_tty2oled.sh```

**Comment by venice1200** [comment]
> Let me know if you need any help with this in the future. And congrats for the awesome project you guys are pulling off.

It would be really great if you add the code from ojaksch.
Cheers

**Comment by theypsilon** [comment]
Hey @venice1200 and @ojaksch , sorry I missed your message a couple of weeks ago.

My intention at least by now, is to not call extra scripts directly from Update All. The fact is that Update All is not an official MiSTer tool and will never be. In the other hand, the Downloader would be integrated in the MiSTer binary at some point. Meaning that there will be an option for downloading updates directly in MiSTer UI without having to go to the "Scripts" menu. Thanks to this, the updating story in MiSTer will end up being way more secure than what we currently have while offering also a much better UX.

Because of this, currently I'm focusing on developing Update All solely as a mean to change INI files through the Settings Screen. That way I'll be preparing the long term transition to a post-Update All updating process. And in the other hand, I'm trying to improve the custom databases feature in the Downloader to support more use cases.

In the next month, Downloader will support zips in custom databases, and that probably will be a good solution for distributing your pictures. Of course, it will never be as fast as rsync, but it will still be very fast. Speed is also one of my top priorities. And I will be testing your scenario to make sure that it performs well enough.

**Comment by ojaksch** [comment]
Thanks for the headup. No hurry at all. We'll have some eyes at your ZIP based update the next weeks.
Proo-oost!
